### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by S-HuaBomb** [mtobeiyf/sketch-to-art#10]
**I run in docker according to the tutorial, but There should be an error with the front end:**

![dcc4c6f96427e1df6bdca047b3704c9](https://user-images.githubusercontent.com/39048551/76479243-1cafe800-6446-11ea-8ade-9bed0683f32b.png)

![0263aa31dd43dcaf0420b03f9ab201d](https://user-images.githubusercontent.com/39048551/76479410-a52e8880-6446-11ea-9ab3-6d7855a86269.png)

**And the two back ends run well:**

![7a3e2a71e182e07f4cf831a20a50892](https://user-images.githubusercontent.com/39048551/76479597-43bae980-6447-11ea-9b88-44fd4315a6e8.png)
![d38af5c57cb6c3b745e8ad7f3867997](https://user-images.githubusercontent.com/39048551/76479605-487f9d80-6447-11ea-9019-2dc4e63a63d6.png)

**What should I do to solve this?**

**Comment by mehdi-elmehdi** [comment]
same problem

**Comment by mtobeiyf** [comment]
I think it's because I forgot to add the command `yarn` before `yarn dev` in the [run.sh](https://github.com/mtobeiyf/sketch-to-art/blob/master/run.sh) file. 
2 solutions:
- You can first run `yarn` locally on your host machine, and then run `docker build` command as described in the README.
- Or, simply add a line `yarn` above the `yarn dev` in the `run.sh` file.

I'll fix this right now.

**Comment by S-HuaBomb** [comment]
That's cool! 💯  I got your email and just simply add a line `yarn` above the `yarn dev` in the `run.sh` file. And it runs well in docker:


![shell](https://user-images.githubusercontent.com/39048551/77218855-dad02180-6b6a-11ea-9ec2-c9e3b0eefcfb.png)

**Comment by mtobeiyf** [comment]
I have fixed this problem 🍻
